// ==========================================
// RailGuardPro v2.0
// script.js
// Part-1
// Paste from Line-1
// ==========================================

// Auto Date
window.onload = function () {

    const today = new Date();

    const yyyy = today.getFullYear();

    const mm = String(today.getMonth() + 1).padStart(2, "0");

    const dd = String(today.getDate()).padStart(2, "0");

    document.getElementById("date").value =
        `${yyyy}-${mm}-${dd}`;

};

// ==========================================
// Generate Report
// ==========================================

function generateReport() {

    const date = document.getElementById("date").value;

    const trainNo = document.getElementById("trainNo").value;

    const dmcNo = document.getElementById("dmcNo").value;

    const lpName = document.getElementById("lpName").value;

    const tmName = document.getElementById("tmName").value;

    const fromStation =
        document.getElementById("fromStation").value;

    const toStation =
        document.getElementById("toStation").value;

    const locoNo =
        document.getElementById("locoNo").value;

    const load =
        document.getElementById("load").value;

    const rakeId =
        document.getElementById("rakeId").value;

    const coachComposition =
        document.getElementById("coachComposition").value;

    const brakePower =
        document.getElementById("brakePower").value;

    const departureTime =
        document.getElementById("departureTime").value;

    const arrivalTime =
        document.getElementById("arrivalTime").value;

    const maxSpeed =
        document.getElementById("maxSpeed").value;

    const weather =
        document.getElementById("weather").value;

    const equipment =
        document.getElementById("equipment").value;

    const remarks =
        document.getElementById("remarks").value;

    const stations =
        document.getElementById("stations").value;

    let report = `
========================================
        RAILGUARDPRO v2.0
      RUNNING REPORT
========================================

Date               : ${date}

Train Number       : ${trainNo}

DMC Number         : ${dmcNo}

Loco Pilot         : ${lpName}

Train Manager      : ${tmName}

From Station       : ${fromStation}

To Station         : ${toStation}

Loco Number        : ${locoNo}

Load               : ${load}

Rake ID            : ${rakeId}

Coach Composition  : ${coachComposition}

Brake Power        : ${brakePower}

Departure Time     : ${departureTime}

Arrival Time       : ${arrivalTime}

Maximum Speed      : ${maxSpeed}

Weather            : ${weather}

Train Equipment
----------------------------------------
${equipment}

`;Running Remarks
----------------------------------------
${remarks}

Stations Passed
----------------------------------------
${stations}

========================================
Report Generated by RailGuardPro v2.0
========================================
`;

    document.getElementById("report").textContent = report;

}// ==========================================
// Copy Report
// ==========================================

function copyReport() {

    const report =
        document.getElementById("report").textContent;

    if(report.trim()===""){

        alert("Please Generate Report First.");

        return;

    }

    navigator.clipboard.writeText(report);

    alert("Running Report Copied Successfully.");

}


// ==========================================
// Clear Form
// ==========================================

function clearForm(){

    document.getElementById("reportForm").reset();

    document.getElementById("report").textContent =
    "Your Professional Running Report will appear here...";

    const today = new Date();

    const yyyy = today.getFullYear();

    const mm = String(today.getMonth()+1).padStart(2,"0");

    const dd = String(today.getDate()).padStart(2,"0");

    document.getElementById("date").value =
    `${yyyy}-${mm}-${dd}`;

}


// ==========================================
// Download Report
// ==========================================

function downloadReport(){

    const report =
    document.getElementById("report").textContent;

    if(report.trim()===""){

        alert("Please Generate Report First.");

        return;

    }

    const blob = new Blob([report],{
        type:"text/plain"
    });

    const link = document.createElement("a");

    link.href = URL.createObjectURL(blob);

    link.download =
    "Running_Report.txt";

    link.click();

}


// ==========================================
// Print Report
// ==========================================

function printReport(){

    const report =
    document.getElementById("report").textContent;

    if(report.trim()===""){

        alert("Please Generate Report First.");

        return;

    }

    const printWindow =
    window.open("","_blank");

    printWindow.document.write(

    "<pre style='font-size:14px;font-family:Consolas;'>"

    + report +

    "</pre>"

    );

    printWindow.document.close();

    printWindow.print();

}// ==========================================
// RailGuardPro v2.0
// Script Part-3
// Validation + Auto Report No.
// ==========================================

// Auto Report Number

function getReportNumber(){

    const now = new Date();

    return "RGP-" +
    now.getFullYear() +
    String(now.getMonth()+1).padStart(2,"0") +
    String(now.getDate()).padStart(2,"0") +
    "-" +
    now.getHours() +
    now.getMinutes() +
    now.getSeconds();

}


// Current Date & Time

function getCurrentDateTime(){

    return new Date().toLocaleString("en-IN");

}


// Validate Required Fields

function validateForm(){

    let requiredFields=[

        "trainNo",
        "lpName",
        "tmName",
        "fromStation",
        "toStation"

    ];

    for(let i=0;i<requiredFields.length;i++){

        let value=document.getElementById(requiredFields[i]).value.trim();

        if(value===""){

            alert("Please Fill All Required Fields.");

            document.getElementById(requiredFields[i]).focus();

            return false;

        }

    }

    return true;

}


// Generate Button Validation

const oldGenerateReport = generateReport;

generateReport = function(){

    if(!validateForm()){

        return;

    }

    oldGenerateReport();

    let report=document.getElementById("report").textContent;

    report += "\n\n";

    report += "----------------------------------------\n";

    report += "Report No : " + getReportNumber() + "\n";

    report += "Generated : " + getCurrentDateTime() + "\n";

    report += "Software  : RailGuardPro v2.0\n";

    report += "Developed By : Munesh Kumar Meena\n";

    report += "----------------------------------------";

    document.getElementById("report").textContent=report;

};


// ==========================================
// End of Part-3
// ==========================================// ==========================================
// RailGuardPro v2.0
// Script Part-4 (Final)
// Auto Save + Auto Restore
// ==========================================

// Save Report

function saveReport(){

    localStorage.setItem(
        "RailGuardPro_Report",
        document.getElementById("report").textContent
    );

}


// Load Last Report

function loadReport(){

    const lastReport =
    localStorage.getItem("RailGuardPro_Report");

    if(lastReport){

        document.getElementById("report").textContent =
        lastReport;

    }

}


// Auto Save after Generate

const previousGenerate = generateReport;

generateReport = function(){

    previousGenerate();

    saveReport();

};


// Clear Local Storage

function clearSavedReport(){

    localStorage.removeItem("RailGuardPro_Report");

}


// Update Clear Button

const previousClear = clearForm;

clearForm = function(){

    previousClear();

    clearSavedReport();

};


// Initialize

window.addEventListener("load",function(){

    loadReport();

});


// ==========================================
// RailGuardPro v2.0
// Script Completed Successfully
// ==========================================